name: Publish
on:
  release:
    types: ["published"]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Building tutorial html files
        run: |
          jupyter-book build ./
      - name: Create a compressed file
        run: tar -zcvf Singularity101.tar.gz _build/html/
      - name: Upload file to release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: Singularity101.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file: Singularity101.tar.gz