name: Publish PDF
on:
  push:
    branches: ["main"]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Building tutorial PDF file
        run: |
          jupyter-book build ./ --builder pdfhtml
      - name: Upload PDF to release
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: Sylabs_Singularity101.pdf
          tag: "PDF"
          #tag: ${{ github.ref }}
          overwrite: true
          file: book.pdf